# Generated by Django 3.2.5 on 2021-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Novel', 'Novel')], default='Manga', max_length=6),
        ),
    ]
