# Generated by Django 3.2.4 on 2021-10-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='categories',
            field=models.TextField(default='All,'),
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='manga',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Novel', 'Novel')], default='Manga', max_length=6),
        ),
    ]
