# Generated by Django 3.2.4 on 2021-10-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211017_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.TextField(blank=True, default=''),
        ),
    ]
