# Generated by Django 3.2.4 on 2021-10-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_extensions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extensions',
            new_name='extension',
        ),
    ]
