# Generated by Django 3.2.4 on 2021-10-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_extensions_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='location',
        ),
        migrations.AddField(
            model_name='extension',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
