# Generated by Django 3.2.4 on 2021-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211018_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='installed',
        ),
        migrations.AddField(
            model_name='extension',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
