# Generated by Django 3.2.5 on 2022-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211127_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('lastRead', models.IntegerField(default=0)),
            ],
        ),
    ]
