# Generated by Django 3.2.4 on 2022-02-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chapter_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='chapters',
        ),
    ]
