# Generated by Django 3.2.4 on 2022-02-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_manga_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='NumChapters',
            field=models.IntegerField(default=0),
        ),
    ]
