# Generated by Django 3.2.5 on 2022-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_manga_numchapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='logo',
            field=models.TextField(default=''),
        ),
    ]
