# Generated by Django 3.2.5 on 2022-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_manga_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='lastRead',
            field=models.IntegerField(default=1),
        ),
    ]
