# Generated by Django 3.2.5 on 2022-03-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_lastread_manga_nextchapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='nextChapter',
        ),
    ]
