# Generated by Django 3.2.5 on 2022-03-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_mangacategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='categorie',
        ),
        migrations.RenameModel(
            old_name='mangaCategories',
            new_name='mangaCategorie',
        ),
    ]
