# Generated by Django 3.2.5 on 2022-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220318_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='leftToRead',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
