# Generated by Django 3.2.5 on 2022-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_manga_lefttoread'),
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterid', models.IntegerField()),
                ('totalPages', models.IntegerField()),
                ('downloaded', models.IntegerField()),
            ],
        ),
    ]
