# Generated by Django 3.2.5 on 2022-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
