# Generated by Django 3.2.5 on 2022-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_chapter_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='downloaded',
            field=models.IntegerField(default=0),
        ),
    ]
