# Generated by Django 3.2.4 on 2022-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220321_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='updating',
            field=models.BooleanField(default=False),
        ),
    ]
