# Generated by Django 3.2.5 on 2022-03-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='category',
        ),
    ]
