# Generated by Django 3.2.4 on 2022-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_mangacategorie_mangacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
