# Generated by Django 3.2.5 on 2022-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_setting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
