# Generated by Django 3.2.5 on 2022-03-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_manga_editing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sources',
        ),
    ]
