# Generated by Django 3.2.5 on 2022-03-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_extension_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='x',
        ),
    ]
