# Generated by Django 3.2.5 on 2022-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_extension_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='extension_url',
            field=models.TextField(default=''),
        ),
    ]
