# Generated by Django 3.2.5 on 2022-03-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_extension_extension_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='extension_url',
            new_name='url',
        ),
    ]
