# Generated by Django 3.2.4 on 2022-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_extension_url_extension_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='chapterName',
            field=models.TextField(default=''),
        ),
    ]
