# Generated by Django 3.2.4 on 2022-04-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_chaptername_download_manganame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='type',
        ),
    ]
