# Generated by Django 3.2.4 on 2022-04-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_manga_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='NumChapters',
            new_name='numChapters',
        ),
    ]
