# Generated by Django 3.2.4 on 2022-04-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_numchapters_manga_numchapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='categories',
        ),
    ]
